/**
 * Automation API provider
 * Automation provides template of this description, and anyone may modify it in your own project.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ClientServiceLevel } from '../model/clientServiceLevel';
import { ClientServiceLevelDto } from '../model/clientServiceLevelDto';
import { PageInfoOfClientServiceLevelDto } from '../model/pageInfoOfClientServiceLevelDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ClientServiceLevelControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * clientServiceLevelBatchDelete
     * 
     * @param ids ids
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelBatchDeleteUsingDELETE(ids: string, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public clientServiceLevelBatchDeleteUsingDELETE(ids: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public clientServiceLevelBatchDeleteUsingDELETE(ids: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public clientServiceLevelBatchDeleteUsingDELETE(ids: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (ids === null || ids === undefined) {
            throw new Error('Required parameter ids was null or undefined when calling clientServiceLevelBatchDeleteUsingDELETE.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ids !== undefined && ids !== null) {
            queryParameters = queryParameters.set('ids', <any>ids);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<number>(`${this.basePath}/masterdata/clientServiceLevel/batch-delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelBatchSave
     * 
     * @param clientServiceLevels clientServiceLevels
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelBatchSaveUsingPOST(clientServiceLevels: Array<ClientServiceLevel>, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public clientServiceLevelBatchSaveUsingPOST(clientServiceLevels: Array<ClientServiceLevel>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public clientServiceLevelBatchSaveUsingPOST(clientServiceLevels: Array<ClientServiceLevel>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public clientServiceLevelBatchSaveUsingPOST(clientServiceLevels: Array<ClientServiceLevel>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientServiceLevels === null || clientServiceLevels === undefined) {
            throw new Error('Required parameter clientServiceLevels was null or undefined when calling clientServiceLevelBatchSaveUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/masterdata/clientServiceLevel/batch-save`,
            clientServiceLevels,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelDelete
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelDeleteUsingDELETE(id: string, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public clientServiceLevelDeleteUsingDELETE(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public clientServiceLevelDeleteUsingDELETE(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public clientServiceLevelDeleteUsingDELETE(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling clientServiceLevelDeleteUsingDELETE.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<number>(`${this.basePath}/masterdata/clientServiceLevel/delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelFilterByName
     * 
     * @param keyWord keyWord
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelFilterByNameUsingGET(keyWord?: string, observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: Array<ClientServiceLevelDto>; }>;
    public clientServiceLevelFilterByNameUsingGET(keyWord?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: Array<ClientServiceLevelDto>; }>>;
    public clientServiceLevelFilterByNameUsingGET(keyWord?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: Array<ClientServiceLevelDto>; }>>;
    public clientServiceLevelFilterByNameUsingGET(keyWord?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (keyWord !== undefined && keyWord !== null) {
            queryParameters = queryParameters.set('keyWord', <any>keyWord);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<{ [key: string]: Array<ClientServiceLevelDto>; }>(`${this.basePath}/masterdata/clientServiceLevel/filter-by`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelFindByColumnsPaged
     * 
     * @param clientServiceLevel clientServiceLevel
     * @param columns columns
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelFindByColumnsPagedUsingPOST(clientServiceLevel: ClientServiceLevel, columns: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ClientServiceLevelDto>>;
    public clientServiceLevelFindByColumnsPagedUsingPOST(clientServiceLevel: ClientServiceLevel, columns: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ClientServiceLevelDto>>>;
    public clientServiceLevelFindByColumnsPagedUsingPOST(clientServiceLevel: ClientServiceLevel, columns: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ClientServiceLevelDto>>>;
    public clientServiceLevelFindByColumnsPagedUsingPOST(clientServiceLevel: ClientServiceLevel, columns: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientServiceLevel === null || clientServiceLevel === undefined) {
            throw new Error('Required parameter clientServiceLevel was null or undefined when calling clientServiceLevelFindByColumnsPagedUsingPOST.');
        }

        if (columns === null || columns === undefined) {
            throw new Error('Required parameter columns was null or undefined when calling clientServiceLevelFindByColumnsPagedUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<ClientServiceLevelDto>>(`${this.basePath}/masterdata/clientServiceLevel/find-by/${encodeURIComponent(String(columns))}`,
            clientServiceLevel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelFindByPaged
     * 
     * @param clientServiceLevel clientServiceLevel
     * @param pageNo page-no
     * @param pageSize page-size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelFindByPagedUsingPOST(clientServiceLevel: ClientServiceLevel, pageNo: number, pageSize: number, observe?: 'body', reportProgress?: boolean): Observable<PageInfoOfClientServiceLevelDto>;
    public clientServiceLevelFindByPagedUsingPOST(clientServiceLevel: ClientServiceLevel, pageNo: number, pageSize: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageInfoOfClientServiceLevelDto>>;
    public clientServiceLevelFindByPagedUsingPOST(clientServiceLevel: ClientServiceLevel, pageNo: number, pageSize: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageInfoOfClientServiceLevelDto>>;
    public clientServiceLevelFindByPagedUsingPOST(clientServiceLevel: ClientServiceLevel, pageNo: number, pageSize: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientServiceLevel === null || clientServiceLevel === undefined) {
            throw new Error('Required parameter clientServiceLevel was null or undefined when calling clientServiceLevelFindByPagedUsingPOST.');
        }

        if (pageNo === null || pageNo === undefined) {
            throw new Error('Required parameter pageNo was null or undefined when calling clientServiceLevelFindByPagedUsingPOST.');
        }

        if (pageSize === null || pageSize === undefined) {
            throw new Error('Required parameter pageSize was null or undefined when calling clientServiceLevelFindByPagedUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PageInfoOfClientServiceLevelDto>(`${this.basePath}/masterdata/clientServiceLevel/find-by-paged/${encodeURIComponent(String(pageNo))}/${encodeURIComponent(String(pageSize))}`,
            clientServiceLevel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelFindBy
     * 
     * @param clientServiceLevelDto clientServiceLevelDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelFindByUsingPOST(clientServiceLevelDto: ClientServiceLevelDto, observe?: 'body', reportProgress?: boolean): Observable<Array<ClientServiceLevelDto>>;
    public clientServiceLevelFindByUsingPOST(clientServiceLevelDto: ClientServiceLevelDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ClientServiceLevelDto>>>;
    public clientServiceLevelFindByUsingPOST(clientServiceLevelDto: ClientServiceLevelDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ClientServiceLevelDto>>>;
    public clientServiceLevelFindByUsingPOST(clientServiceLevelDto: ClientServiceLevelDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientServiceLevelDto === null || clientServiceLevelDto === undefined) {
            throw new Error('Required parameter clientServiceLevelDto was null or undefined when calling clientServiceLevelFindByUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<ClientServiceLevelDto>>(`${this.basePath}/masterdata/clientServiceLevel/find-by`,
            clientServiceLevelDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelFindOne
     * 
     * @param fieldName fieldName
     * @param value value
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelFindOneUsingGET(fieldName: string, value: string, observe?: 'body', reportProgress?: boolean): Observable<ClientServiceLevelDto>;
    public clientServiceLevelFindOneUsingGET(fieldName: string, value: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ClientServiceLevelDto>>;
    public clientServiceLevelFindOneUsingGET(fieldName: string, value: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ClientServiceLevelDto>>;
    public clientServiceLevelFindOneUsingGET(fieldName: string, value: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fieldName === null || fieldName === undefined) {
            throw new Error('Required parameter fieldName was null or undefined when calling clientServiceLevelFindOneUsingGET.');
        }

        if (value === null || value === undefined) {
            throw new Error('Required parameter value was null or undefined when calling clientServiceLevelFindOneUsingGET.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (fieldName !== undefined && fieldName !== null) {
            queryParameters = queryParameters.set('fieldName', <any>fieldName);
        }
        if (value !== undefined && value !== null) {
            queryParameters = queryParameters.set('value', <any>value);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ClientServiceLevelDto>(`${this.basePath}/masterdata/clientServiceLevel/find-one`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelFind
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelFindUsingGET(id: string, observe?: 'body', reportProgress?: boolean): Observable<ClientServiceLevelDto>;
    public clientServiceLevelFindUsingGET(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ClientServiceLevelDto>>;
    public clientServiceLevelFindUsingGET(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ClientServiceLevelDto>>;
    public clientServiceLevelFindUsingGET(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling clientServiceLevelFindUsingGET.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ClientServiceLevelDto>(`${this.basePath}/masterdata/clientServiceLevel/find`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelListPaged
     * 
     * @param pageNo page-no
     * @param pageSize page-size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelListPagedUsingGET(pageNo: number, pageSize: number, observe?: 'body', reportProgress?: boolean): Observable<PageInfoOfClientServiceLevelDto>;
    public clientServiceLevelListPagedUsingGET(pageNo: number, pageSize: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageInfoOfClientServiceLevelDto>>;
    public clientServiceLevelListPagedUsingGET(pageNo: number, pageSize: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageInfoOfClientServiceLevelDto>>;
    public clientServiceLevelListPagedUsingGET(pageNo: number, pageSize: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (pageNo === null || pageNo === undefined) {
            throw new Error('Required parameter pageNo was null or undefined when calling clientServiceLevelListPagedUsingGET.');
        }

        if (pageSize === null || pageSize === undefined) {
            throw new Error('Required parameter pageSize was null or undefined when calling clientServiceLevelListPagedUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PageInfoOfClientServiceLevelDto>(`${this.basePath}/masterdata/clientServiceLevel/list-paged/${encodeURIComponent(String(pageNo))}/${encodeURIComponent(String(pageSize))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelList
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelListUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<ClientServiceLevelDto>>;
    public clientServiceLevelListUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ClientServiceLevelDto>>>;
    public clientServiceLevelListUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ClientServiceLevelDto>>>;
    public clientServiceLevelListUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ClientServiceLevelDto>>(`${this.basePath}/masterdata/clientServiceLevel/list`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelSave
     * 
     * @param clientServiceLevel clientServiceLevel
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelSaveUsingPOST(clientServiceLevel: ClientServiceLevel, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public clientServiceLevelSaveUsingPOST(clientServiceLevel: ClientServiceLevel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public clientServiceLevelSaveUsingPOST(clientServiceLevel: ClientServiceLevel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public clientServiceLevelSaveUsingPOST(clientServiceLevel: ClientServiceLevel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientServiceLevel === null || clientServiceLevel === undefined) {
            throw new Error('Required parameter clientServiceLevel was null or undefined when calling clientServiceLevelSaveUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/masterdata/clientServiceLevel/save`,
            clientServiceLevel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * clientServiceLevelUpdate
     * 
     * @param clientServiceLevel clientServiceLevel
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientServiceLevelUpdateUsingPUT(clientServiceLevel: ClientServiceLevel, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public clientServiceLevelUpdateUsingPUT(clientServiceLevel: ClientServiceLevel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public clientServiceLevelUpdateUsingPUT(clientServiceLevel: ClientServiceLevel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public clientServiceLevelUpdateUsingPUT(clientServiceLevel: ClientServiceLevel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientServiceLevel === null || clientServiceLevel === undefined) {
            throw new Error('Required parameter clientServiceLevel was null or undefined when calling clientServiceLevelUpdateUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<number>(`${this.basePath}/masterdata/clientServiceLevel/update`,
            clientServiceLevel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
