/**
 * Automation API provider
 * Automation provides template of this description, and anyone may modify it in your own project.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CompanyServiceLevel } from '../model/companyServiceLevel';
import { CompanyServiceLevelDto } from '../model/companyServiceLevelDto';
import { PageInfoOfCompanyServiceLevelDto } from '../model/pageInfoOfCompanyServiceLevelDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CompanyServiceLevelControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * companyServiceLevelBatchDelete
     * 
     * @param ids ids
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelBatchDeleteUsingDELETE(ids: string, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public companyServiceLevelBatchDeleteUsingDELETE(ids: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public companyServiceLevelBatchDeleteUsingDELETE(ids: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public companyServiceLevelBatchDeleteUsingDELETE(ids: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (ids === null || ids === undefined) {
            throw new Error('Required parameter ids was null or undefined when calling companyServiceLevelBatchDeleteUsingDELETE.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ids !== undefined && ids !== null) {
            queryParameters = queryParameters.set('ids', <any>ids);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<number>(`${this.basePath}/masterdata/companyServiceLevel/batch-delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelBatchSave
     * 
     * @param companyServiceLevels companyServiceLevels
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelBatchSaveUsingPOST(companyServiceLevels: Array<CompanyServiceLevel>, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public companyServiceLevelBatchSaveUsingPOST(companyServiceLevels: Array<CompanyServiceLevel>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public companyServiceLevelBatchSaveUsingPOST(companyServiceLevels: Array<CompanyServiceLevel>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public companyServiceLevelBatchSaveUsingPOST(companyServiceLevels: Array<CompanyServiceLevel>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (companyServiceLevels === null || companyServiceLevels === undefined) {
            throw new Error('Required parameter companyServiceLevels was null or undefined when calling companyServiceLevelBatchSaveUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/masterdata/companyServiceLevel/batch-save`,
            companyServiceLevels,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelDelete
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelDeleteUsingDELETE(id: string, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public companyServiceLevelDeleteUsingDELETE(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public companyServiceLevelDeleteUsingDELETE(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public companyServiceLevelDeleteUsingDELETE(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling companyServiceLevelDeleteUsingDELETE.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<number>(`${this.basePath}/masterdata/companyServiceLevel/delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelFindByColumnsPaged
     * 
     * @param columns columns
     * @param companyServiceLevel companyServiceLevel
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelFindByColumnsPagedUsingPOST(columns: string, companyServiceLevel: CompanyServiceLevel, observe?: 'body', reportProgress?: boolean): Observable<Array<CompanyServiceLevelDto>>;
    public companyServiceLevelFindByColumnsPagedUsingPOST(columns: string, companyServiceLevel: CompanyServiceLevel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CompanyServiceLevelDto>>>;
    public companyServiceLevelFindByColumnsPagedUsingPOST(columns: string, companyServiceLevel: CompanyServiceLevel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CompanyServiceLevelDto>>>;
    public companyServiceLevelFindByColumnsPagedUsingPOST(columns: string, companyServiceLevel: CompanyServiceLevel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (columns === null || columns === undefined) {
            throw new Error('Required parameter columns was null or undefined when calling companyServiceLevelFindByColumnsPagedUsingPOST.');
        }

        if (companyServiceLevel === null || companyServiceLevel === undefined) {
            throw new Error('Required parameter companyServiceLevel was null or undefined when calling companyServiceLevelFindByColumnsPagedUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<CompanyServiceLevelDto>>(`${this.basePath}/masterdata/companyServiceLevel/find-by/${encodeURIComponent(String(columns))}`,
            companyServiceLevel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelFindByPaged
     * 
     * @param companyServiceLevel companyServiceLevel
     * @param pageNo page-no
     * @param pageSize page-size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelFindByPagedUsingPOST(companyServiceLevel: CompanyServiceLevel, pageNo: number, pageSize: number, observe?: 'body', reportProgress?: boolean): Observable<PageInfoOfCompanyServiceLevelDto>;
    public companyServiceLevelFindByPagedUsingPOST(companyServiceLevel: CompanyServiceLevel, pageNo: number, pageSize: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageInfoOfCompanyServiceLevelDto>>;
    public companyServiceLevelFindByPagedUsingPOST(companyServiceLevel: CompanyServiceLevel, pageNo: number, pageSize: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageInfoOfCompanyServiceLevelDto>>;
    public companyServiceLevelFindByPagedUsingPOST(companyServiceLevel: CompanyServiceLevel, pageNo: number, pageSize: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (companyServiceLevel === null || companyServiceLevel === undefined) {
            throw new Error('Required parameter companyServiceLevel was null or undefined when calling companyServiceLevelFindByPagedUsingPOST.');
        }

        if (pageNo === null || pageNo === undefined) {
            throw new Error('Required parameter pageNo was null or undefined when calling companyServiceLevelFindByPagedUsingPOST.');
        }

        if (pageSize === null || pageSize === undefined) {
            throw new Error('Required parameter pageSize was null or undefined when calling companyServiceLevelFindByPagedUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PageInfoOfCompanyServiceLevelDto>(`${this.basePath}/masterdata/companyServiceLevel/find-by-paged/${encodeURIComponent(String(pageNo))}/${encodeURIComponent(String(pageSize))}`,
            companyServiceLevel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelFindBy
     * 
     * @param companyServiceLevelDto companyServiceLevelDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelFindByUsingPOST(companyServiceLevelDto: CompanyServiceLevelDto, observe?: 'body', reportProgress?: boolean): Observable<Array<CompanyServiceLevelDto>>;
    public companyServiceLevelFindByUsingPOST(companyServiceLevelDto: CompanyServiceLevelDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CompanyServiceLevelDto>>>;
    public companyServiceLevelFindByUsingPOST(companyServiceLevelDto: CompanyServiceLevelDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CompanyServiceLevelDto>>>;
    public companyServiceLevelFindByUsingPOST(companyServiceLevelDto: CompanyServiceLevelDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (companyServiceLevelDto === null || companyServiceLevelDto === undefined) {
            throw new Error('Required parameter companyServiceLevelDto was null or undefined when calling companyServiceLevelFindByUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<CompanyServiceLevelDto>>(`${this.basePath}/masterdata/companyServiceLevel/find-by`,
            companyServiceLevelDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelFindOne
     * 
     * @param fieldName fieldName
     * @param value value
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelFindOneUsingGET(fieldName: string, value: string, observe?: 'body', reportProgress?: boolean): Observable<CompanyServiceLevelDto>;
    public companyServiceLevelFindOneUsingGET(fieldName: string, value: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CompanyServiceLevelDto>>;
    public companyServiceLevelFindOneUsingGET(fieldName: string, value: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CompanyServiceLevelDto>>;
    public companyServiceLevelFindOneUsingGET(fieldName: string, value: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fieldName === null || fieldName === undefined) {
            throw new Error('Required parameter fieldName was null or undefined when calling companyServiceLevelFindOneUsingGET.');
        }

        if (value === null || value === undefined) {
            throw new Error('Required parameter value was null or undefined when calling companyServiceLevelFindOneUsingGET.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (fieldName !== undefined && fieldName !== null) {
            queryParameters = queryParameters.set('fieldName', <any>fieldName);
        }
        if (value !== undefined && value !== null) {
            queryParameters = queryParameters.set('value', <any>value);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CompanyServiceLevelDto>(`${this.basePath}/masterdata/companyServiceLevel/find-one`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelFind
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelFindUsingGET(id: string, observe?: 'body', reportProgress?: boolean): Observable<CompanyServiceLevelDto>;
    public companyServiceLevelFindUsingGET(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CompanyServiceLevelDto>>;
    public companyServiceLevelFindUsingGET(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CompanyServiceLevelDto>>;
    public companyServiceLevelFindUsingGET(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling companyServiceLevelFindUsingGET.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CompanyServiceLevelDto>(`${this.basePath}/masterdata/companyServiceLevel/find`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelListPaged
     * 
     * @param pageNo page-no
     * @param pageSize page-size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelListPagedUsingGET(pageNo: number, pageSize: number, observe?: 'body', reportProgress?: boolean): Observable<PageInfoOfCompanyServiceLevelDto>;
    public companyServiceLevelListPagedUsingGET(pageNo: number, pageSize: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageInfoOfCompanyServiceLevelDto>>;
    public companyServiceLevelListPagedUsingGET(pageNo: number, pageSize: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageInfoOfCompanyServiceLevelDto>>;
    public companyServiceLevelListPagedUsingGET(pageNo: number, pageSize: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (pageNo === null || pageNo === undefined) {
            throw new Error('Required parameter pageNo was null or undefined when calling companyServiceLevelListPagedUsingGET.');
        }

        if (pageSize === null || pageSize === undefined) {
            throw new Error('Required parameter pageSize was null or undefined when calling companyServiceLevelListPagedUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PageInfoOfCompanyServiceLevelDto>(`${this.basePath}/masterdata/companyServiceLevel/list-paged/${encodeURIComponent(String(pageNo))}/${encodeURIComponent(String(pageSize))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelList
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelListUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<CompanyServiceLevelDto>>;
    public companyServiceLevelListUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CompanyServiceLevelDto>>>;
    public companyServiceLevelListUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CompanyServiceLevelDto>>>;
    public companyServiceLevelListUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<CompanyServiceLevelDto>>(`${this.basePath}/masterdata/companyServiceLevel/list`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelSave
     * 
     * @param companyServiceLevel companyServiceLevel
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelSaveUsingPOST(companyServiceLevel: CompanyServiceLevel, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public companyServiceLevelSaveUsingPOST(companyServiceLevel: CompanyServiceLevel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public companyServiceLevelSaveUsingPOST(companyServiceLevel: CompanyServiceLevel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public companyServiceLevelSaveUsingPOST(companyServiceLevel: CompanyServiceLevel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (companyServiceLevel === null || companyServiceLevel === undefined) {
            throw new Error('Required parameter companyServiceLevel was null or undefined when calling companyServiceLevelSaveUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/masterdata/companyServiceLevel/save`,
            companyServiceLevel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * companyServiceLevelUpdate
     * 
     * @param companyServiceLevel companyServiceLevel
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companyServiceLevelUpdateUsingPUT(companyServiceLevel: CompanyServiceLevel, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public companyServiceLevelUpdateUsingPUT(companyServiceLevel: CompanyServiceLevel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public companyServiceLevelUpdateUsingPUT(companyServiceLevel: CompanyServiceLevel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public companyServiceLevelUpdateUsingPUT(companyServiceLevel: CompanyServiceLevel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (companyServiceLevel === null || companyServiceLevel === undefined) {
            throw new Error('Required parameter companyServiceLevel was null or undefined when calling companyServiceLevelUpdateUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<number>(`${this.basePath}/masterdata/companyServiceLevel/update`,
            companyServiceLevel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
