/**
 * Automation API provider
 * Automation provides template of this description, and anyone may modify it in your own project.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CutoffTime } from '../model/cutoffTime';
import { CutoffTimeDto } from '../model/cutoffTimeDto';
import { PageInfoOfCutoffTimeDto } from '../model/pageInfoOfCutoffTimeDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CutoffTimeControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * cutoffTimeBatchDelete
     * 
     * @param ids ids
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeBatchDeleteUsingDELETE(ids: string, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public cutoffTimeBatchDeleteUsingDELETE(ids: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public cutoffTimeBatchDeleteUsingDELETE(ids: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public cutoffTimeBatchDeleteUsingDELETE(ids: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (ids === null || ids === undefined) {
            throw new Error('Required parameter ids was null or undefined when calling cutoffTimeBatchDeleteUsingDELETE.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ids !== undefined && ids !== null) {
            queryParameters = queryParameters.set('ids', <any>ids);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<number>(`${this.basePath}/masterdata/cutoffTime/batch-delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeBatchSave
     * 
     * @param cutoffTimes cutoffTimes
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeBatchSaveUsingPOST(cutoffTimes: Array<CutoffTime>, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public cutoffTimeBatchSaveUsingPOST(cutoffTimes: Array<CutoffTime>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public cutoffTimeBatchSaveUsingPOST(cutoffTimes: Array<CutoffTime>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public cutoffTimeBatchSaveUsingPOST(cutoffTimes: Array<CutoffTime>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cutoffTimes === null || cutoffTimes === undefined) {
            throw new Error('Required parameter cutoffTimes was null or undefined when calling cutoffTimeBatchSaveUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/masterdata/cutoffTime/batch-save`,
            cutoffTimes,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeDelete
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeDeleteUsingDELETE(id: string, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public cutoffTimeDeleteUsingDELETE(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public cutoffTimeDeleteUsingDELETE(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public cutoffTimeDeleteUsingDELETE(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling cutoffTimeDeleteUsingDELETE.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<number>(`${this.basePath}/masterdata/cutoffTime/delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeFindByColumnsPaged
     * 
     * @param columns columns
     * @param cutoffTime cutoffTime
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeFindByColumnsPagedUsingPOST(columns: string, cutoffTime: CutoffTime, observe?: 'body', reportProgress?: boolean): Observable<Array<CutoffTime>>;
    public cutoffTimeFindByColumnsPagedUsingPOST(columns: string, cutoffTime: CutoffTime, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CutoffTime>>>;
    public cutoffTimeFindByColumnsPagedUsingPOST(columns: string, cutoffTime: CutoffTime, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CutoffTime>>>;
    public cutoffTimeFindByColumnsPagedUsingPOST(columns: string, cutoffTime: CutoffTime, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (columns === null || columns === undefined) {
            throw new Error('Required parameter columns was null or undefined when calling cutoffTimeFindByColumnsPagedUsingPOST.');
        }

        if (cutoffTime === null || cutoffTime === undefined) {
            throw new Error('Required parameter cutoffTime was null or undefined when calling cutoffTimeFindByColumnsPagedUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<CutoffTime>>(`${this.basePath}/masterdata/cutoffTime/find-by/${encodeURIComponent(String(columns))}`,
            cutoffTime,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeFindByPaged
     * 
     * @param cutoffTime cutoffTime
     * @param pageNo page-no
     * @param pageSize page-size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeFindByPagedUsingPOST(cutoffTime: CutoffTime, pageNo: number, pageSize: number, observe?: 'body', reportProgress?: boolean): Observable<PageInfoOfCutoffTimeDto>;
    public cutoffTimeFindByPagedUsingPOST(cutoffTime: CutoffTime, pageNo: number, pageSize: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageInfoOfCutoffTimeDto>>;
    public cutoffTimeFindByPagedUsingPOST(cutoffTime: CutoffTime, pageNo: number, pageSize: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageInfoOfCutoffTimeDto>>;
    public cutoffTimeFindByPagedUsingPOST(cutoffTime: CutoffTime, pageNo: number, pageSize: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cutoffTime === null || cutoffTime === undefined) {
            throw new Error('Required parameter cutoffTime was null or undefined when calling cutoffTimeFindByPagedUsingPOST.');
        }

        if (pageNo === null || pageNo === undefined) {
            throw new Error('Required parameter pageNo was null or undefined when calling cutoffTimeFindByPagedUsingPOST.');
        }

        if (pageSize === null || pageSize === undefined) {
            throw new Error('Required parameter pageSize was null or undefined when calling cutoffTimeFindByPagedUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PageInfoOfCutoffTimeDto>(`${this.basePath}/masterdata/cutoffTime/find-by-paged/${encodeURIComponent(String(pageNo))}/${encodeURIComponent(String(pageSize))}`,
            cutoffTime,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeFindBy
     * 
     * @param cutoffTime cutoffTime
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeFindByUsingPOST(cutoffTime: CutoffTime, observe?: 'body', reportProgress?: boolean): Observable<Array<CutoffTimeDto>>;
    public cutoffTimeFindByUsingPOST(cutoffTime: CutoffTime, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CutoffTimeDto>>>;
    public cutoffTimeFindByUsingPOST(cutoffTime: CutoffTime, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CutoffTimeDto>>>;
    public cutoffTimeFindByUsingPOST(cutoffTime: CutoffTime, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cutoffTime === null || cutoffTime === undefined) {
            throw new Error('Required parameter cutoffTime was null or undefined when calling cutoffTimeFindByUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<CutoffTimeDto>>(`${this.basePath}/masterdata/cutoffTime/find-by`,
            cutoffTime,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeFindOne
     * 
     * @param fieldName fieldName
     * @param value value
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeFindOneUsingGET(fieldName: string, value: string, observe?: 'body', reportProgress?: boolean): Observable<CutoffTimeDto>;
    public cutoffTimeFindOneUsingGET(fieldName: string, value: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CutoffTimeDto>>;
    public cutoffTimeFindOneUsingGET(fieldName: string, value: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CutoffTimeDto>>;
    public cutoffTimeFindOneUsingGET(fieldName: string, value: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fieldName === null || fieldName === undefined) {
            throw new Error('Required parameter fieldName was null or undefined when calling cutoffTimeFindOneUsingGET.');
        }

        if (value === null || value === undefined) {
            throw new Error('Required parameter value was null or undefined when calling cutoffTimeFindOneUsingGET.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (fieldName !== undefined && fieldName !== null) {
            queryParameters = queryParameters.set('fieldName', <any>fieldName);
        }
        if (value !== undefined && value !== null) {
            queryParameters = queryParameters.set('value', <any>value);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CutoffTimeDto>(`${this.basePath}/masterdata/cutoffTime/find-one`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeFind
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeFindUsingGET(id: string, observe?: 'body', reportProgress?: boolean): Observable<CutoffTimeDto>;
    public cutoffTimeFindUsingGET(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CutoffTimeDto>>;
    public cutoffTimeFindUsingGET(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CutoffTimeDto>>;
    public cutoffTimeFindUsingGET(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling cutoffTimeFindUsingGET.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CutoffTimeDto>(`${this.basePath}/masterdata/cutoffTime/find`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeListPaged
     * 
     * @param pageNo page-no
     * @param pageSize page-size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeListPagedUsingGET(pageNo: number, pageSize: number, observe?: 'body', reportProgress?: boolean): Observable<PageInfoOfCutoffTimeDto>;
    public cutoffTimeListPagedUsingGET(pageNo: number, pageSize: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageInfoOfCutoffTimeDto>>;
    public cutoffTimeListPagedUsingGET(pageNo: number, pageSize: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageInfoOfCutoffTimeDto>>;
    public cutoffTimeListPagedUsingGET(pageNo: number, pageSize: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (pageNo === null || pageNo === undefined) {
            throw new Error('Required parameter pageNo was null or undefined when calling cutoffTimeListPagedUsingGET.');
        }

        if (pageSize === null || pageSize === undefined) {
            throw new Error('Required parameter pageSize was null or undefined when calling cutoffTimeListPagedUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PageInfoOfCutoffTimeDto>(`${this.basePath}/masterdata/cutoffTime/list-paged/${encodeURIComponent(String(pageNo))}/${encodeURIComponent(String(pageSize))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeList
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeListUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<CutoffTimeDto>>;
    public cutoffTimeListUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CutoffTimeDto>>>;
    public cutoffTimeListUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CutoffTimeDto>>>;
    public cutoffTimeListUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<CutoffTimeDto>>(`${this.basePath}/masterdata/cutoffTime/list`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeSave
     * 
     * @param cutoffTime cutoffTime
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeSaveUsingPOST(cutoffTime: CutoffTime, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public cutoffTimeSaveUsingPOST(cutoffTime: CutoffTime, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public cutoffTimeSaveUsingPOST(cutoffTime: CutoffTime, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public cutoffTimeSaveUsingPOST(cutoffTime: CutoffTime, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cutoffTime === null || cutoffTime === undefined) {
            throw new Error('Required parameter cutoffTime was null or undefined when calling cutoffTimeSaveUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/masterdata/cutoffTime/save`,
            cutoffTime,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cutoffTimeUpdate
     * 
     * @param cutoffTime cutoffTime
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cutoffTimeUpdateUsingPUT(cutoffTime: CutoffTime, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public cutoffTimeUpdateUsingPUT(cutoffTime: CutoffTime, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public cutoffTimeUpdateUsingPUT(cutoffTime: CutoffTime, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public cutoffTimeUpdateUsingPUT(cutoffTime: CutoffTime, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cutoffTime === null || cutoffTime === undefined) {
            throw new Error('Required parameter cutoffTime was null or undefined when calling cutoffTimeUpdateUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<number>(`${this.basePath}/masterdata/cutoffTime/update`,
            cutoffTime,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
